#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

apt update

apt install -y nginx

echo "server 54.157.189.169 {
    listen 80;
    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

service nginx start

update-rc.d nginx enable

exit 0
