#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

apt update

apt install -y nginx

echo "server {
    listen 80;
    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

service nginx start

exit 0
