#!/usr/bin/env bash
# Script to configure a Ubuntu machine for redirection

apt update

apt install -y nginx

echo "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }

    location / {
        return 200 'Hello WOrld';
    }
}" > /etc/nginx/sites-available/default

service nginx enable

exit 0
