#!/usr/bin/env bash
# Script to configure a Ubuntu machine for redirection

apt update

apt install -y nginx

echo "server _ {
    listen 80;
    
    location / {
        return 200 'Hello World';
    }

    location = /redirect_me {
        return 301 'Moved Permanently';
    }
}" > /etc/nginx/sites-available/default

service nginx enable

exit 0
