#!/usr/bin/env bash
# Script to configure a Ubuntu machine for redirection

apt update

apt install -y nginx

echo "server {
    listen 80;
    server_name _;
    
    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;

    location = /404.html {
	return 404 Ceci n'\''est pas une page;
    }

}" > /etc/nginx/sites-available/default

service nginx enable

exit 0
