#!/usr/bin/env bash
#Script to install nginx

sudo apt update

sudo apt install -y nginx

echo "server default server{
    listen 80 default server;
    listen [::]:80;

    server_name _;

    location / {
        add_header X-Served_by 190045-web-01
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

sudo ufw enable

sudo ufw allow OpenSSH

sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'

sudo nginx -t

sudo service nginx restart


exit 0
