#!/usr/bin/env bash
# Bash script to fix a bug that is causing nginx to not use port 80

sudo apt-get update

sudo apt-get nginx

# Configure Nginx
echo "server {
    listen 80;
    server_name _;
    root /var/www/html;


    location / {
    }
}" > /etc/nginx/config

# Restart Nginx
sudo service nginx restart

