#!/usr/bin/env bash

# Script to kill process 7-highlander

# Get the PID of the process
PID=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -z "$PID" ]; then
	no-op
else
	kill -TERM "$PID"
fi
