#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

x=1
while [ $x -le 10 ]
do
	echo "Best School"
	if ((x == 4)); then
		echo "bad luck"
	elif ((x == 8)); then
		echo "good luck"
	fi
	x=$(( x + 1 ))
done
