#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

x=1
while [ $x -le 20 ];
do
	case $x in
		exit) break ;;
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	echo "$x"
	x=$(( x + 1 ))
done
