#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

x=1
while [ $x -le 20 ];
do
	case $x in
		exit) break ;;
		5) echo "bad luck from China" ;;
		10) echo "bad luck from Japan" ;;
		18) echo "bad luck from Italy" ;;
	esac
	echo "$x"
	x=$(( x + 1 ))
done
