#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

begin_hour=$(date +%H)
begin_mins=$(date +%M)

time_limit_in_hours=13
time_limit_in_mins=59

i=0
j=0

while [[ $i -lt time_limit_in_hours ]]; do
	echo "Hour: $i";
	while [[ $j -lt time_limit_in_mins ]]; do
		echo $j;
		((j++));
	done
	((i++));
done
