#!/usr/bin/env bash
#Script to configure an Ubuntu server

#Backup the original
cp /etc/hosts ~/hosts.new

#Replace IP addresses and add new entries
sed -i '/^127\.0\.0\.1/ s/ .*/ localhost/' ~/host.new
sed -i '/^127\.0\.1\.1/ s/ .*/ localhost.localdomain/' ~/hosts.new
sed -i 's/^127\.0\.0\.2.*/127.0.0.2 localhost/' ~/host.new
sed -i 's/^8\.8\.8\.8.*/8.8.8.8 facebook.com/' ~/hosts.new

#Overwrite the original file with the backup file
sudo cp -f ~/hosts.new /etc/hosts
