#!/usr/bin/env bash
#Script to configure an Ubuntu server

#Backup the original
cp /etc/hosts ~/hosts.new

#Replace IP addresses and add new entries
sed -i '/^127\.0\.0\.1/ .*/ localhost/' ~/hosts.new
sed -i '/^127\.0\.1\.1/ .*/ localhost.localdomain/' ~/hosts.new
sed -i '/^127\.0\.0\.2.*/127.0.0.2 localhost/' ~/hosts.new
sed -i '/^8\.8\.8\.8.*/8.8.8.8 facebook.com/' ~/hosts.new

#Overwrite the original file with the backup file
cat ~/hosts.new > /etc/hosts
