#!/usr/bin/env bash
#Script to configure an Ubuntu server

#Backup the original
cp /etc/hosts ~/hosts.new

#Replace IP addresses and add new entries
sed -i 's/^127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/host.new
#Overwrite the original file with the backup file
sudo cp -f ~/hosts.new /etc/hosts

#Remove the temporary file
rm ~/hosts.new
