#!/usr/bin/env bash
# Script: 0-iamsomeoneelse
# Description: This script accepts one arguement and run whoami command
#              under the specified user. It checks if the user exists

if [ $# -ne 1 ]; then
    exit 1
fi

username="$1"

#Check if the user exists
if id "$username" &>/dev/null; then
    #Run the whoami command
    sudo -u "$username" whoami
else
    exit 1
fi
