#!/usr/bin/env bash
#Script to take arguement and run whoami command under the specified user

if [ $# -ne 1 ]; then
    exit 1
fi

username="$1"

#Check if the user exists
if id "$username" &>/dev/null; then
    #Run the whoami command
    sudo -u "$username" whoami
else
    exit 1
fi
