#!/usr/bin/env bash

if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install -y nginx
fi

service nginx stop

sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx start

echo "Nginx is now configured to run as nginx user and listen on all active IPs on port 8080."
