#!/usr/bin/env bash
#script to limit privildges to nginx

sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

sudo systemctl stop apache2

sudo service nginx restart

echo "Nginx privileges have been limited."
