#!/usr/bin/bash
# Script to configure nginx server

sudo echo 'server {
    listen 80 default_server;
    server_name _;


    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
    }

    header:
    add_header X-Served-By "190045-web-01";

    root /var/www/html;

    listen [::]:80 default_server;

    index index.html index.htm index.nginx-dbian.html;

    location / {
        # Additional configuration for other routes or files
        # If necessary
        try_files $uri $uri/ =404;
    }
}' > /etc/nginx/sites-available/default

sudo service nginx enable
